# ============================================
# 
# Sample docker file to test builds
# 
# ============================================

# Base image
FROM alpine

# Command for testing
CMD ["/bin/echo", "OK"]
