# ============================================
# 
# Sample docker file to test builds
# 
# ============================================

# Base image
FROM alpine

# Maintainer
MAINTAINER alban.montaigu@gmail.com

# Command for testing
CMD ["/bin/echo", "OK"]
